In [21]:
def leven(x, y):
    n = len(x)
    m = len(y)

    A = [[i + j for j in range(m + 1)] for i in range(n + 1)]

    for i in range(n):
        for j in range(m):
            A[i + 1][j + 1] = min(A[i][j + 1] + 1,              # insert
                                  A[i + 1][j] + 1,              # delete
                                  A[i][j] + int(x[i] != y[j]))  # replace

    return A[n][m]


print(leven("algorithm","alligator"))


6


In [18]:
import numpy

def levenshteinDistanceDP(token1, token2):
    distances = numpy.zeros((len(token1) + 1, len(token2) + 1))

    for t1 in range(len(token1) + 1):
        distances[t1][0] = t1

    for t2 in range(len(token2) + 1):
        distances[0][t2] = t2
        
    a = 0
    b = 0
    c = 0
    
    for t1 in range(1, len(token1) + 1):
        for t2 in range(1, len(token2) + 1):
            if (token1[t1-1] == token2[t2-1]):
                distances[t1][t2] = distances[t1 - 1][t2 - 1]
            else:
                a = distances[t1][t2 - 1]
                b = distances[t1 - 1][t2]
                c = distances[t1 - 1][t2 - 1]
                
                if (a <= b and a <= c):
                    distances[t1][t2] = a + 1
                elif (b <= a and b <= c):
                    distances[t1][t2] = b + 1
                else:
                    distances[t1][t2] = c + 1

    print(distances, len(token1), len(token2))
    return distances[len(token1)][len(token2)]

distance = levenshteinDistanceDP("algorithm", "alligator")

[[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [1. 0. 1. 2. 3. 4. 5. 6. 7. 8.]
 [2. 1. 0. 1. 2. 3. 4. 5. 6. 7.]
 [3. 2. 1. 1. 2. 2. 3. 4. 5. 6.]
 [4. 3. 2. 2. 2. 3. 3. 4. 4. 5.]
 [5. 4. 3. 3. 3. 3. 4. 4. 5. 4.]
 [6. 5. 4. 4. 3. 4. 4. 5. 5. 5.]
 [7. 6. 5. 5. 4. 4. 5. 4. 5. 6.]
 [8. 7. 6. 6. 5. 5. 5. 5. 5. 6.]
 [9. 8. 7. 7. 6. 6. 6. 6. 6. 6.]] 9 9


In [33]:
# Calculates the levenshtein distance and the edits between two strings
def levenshtein(s1, s2, key=hash):
  rows = costmatrix(s1, s2, key)
  edits = backtrace(s1, s2, rows, key)
 
  return rows[-1][-1], edits
 
# Generate the cost matrix for the two strings
# Based on http://en.wikibooks.org/wiki/Algorithm_Implementation/Strings/Levenshtein_distance#Python
def costmatrix(s1, s2, key=hash):
  rows = []
 
  previous_row = range(len(s2) + 1)
  rows.append(list(previous_row))

  insertionCost = 20
  deletetionCost = 20
  substitutionsCost = 5
 
  for i, c1 in enumerate(s1):
    current_row = [i + 1]
    for j, c2 in enumerate(s2):
      insertions = (previous_row[j + 1]) + insersionCost
      deletions = (current_row[j]) + deletetionCost
      substitutions = (previous_row[j] + (key(c1) != key(c2))) + substitutionsCost
      print("This is insertions: " + str(insertions))
      print("This is delete: " + str(deletions))
      print("This is subs: " + str(substitutions))

      current_row.append(min(insertions, deletions, substitutions))
    previous_row = current_row
 
    rows.append(previous_row)
 
  return rows
 
# Trace back through the cost matrix to generate the list of edits
def backtrace(s1, s2, rows, key=hash):
  i, j = len(s1), len(s2)
 
  edits = []
 
  while(not (i == 0  and j == 0)):
    prev_cost = rows[i][j]
 
    neighbors = []
 
    if(i!=0 and j!=0):
      neighbors.append(rows[i-1][j-1])
    if(i!=0):
      neighbors.append(rows[i-1][j])
    if(j!=0):
      neighbors.append(rows[i][j-1])
 
    min_cost = min(neighbors)
 
    if(min_cost == prev_cost):
      i, j = i-1, j-1
      edits.append({'type':'match', 'i':i, 'j':j})
    elif(i!=0 and j!=0 and min_cost == rows[i-1][j-1]):
      i, j = i-1, j-1
      edits.append({'type':'substitution', 'i':i, 'j':j})
    elif(i!=0 and min_cost == rows[i-1][j]):
      i, j = i-1, j
      edits.append({'type':'deletion', 'i':i, 'j':j})
    elif(j!=0 and min_cost == rows[i][j-1]):
      i, j = i, j-1
      edits.append({'type':'insertion', 'i':i, 'j':j})
 
  edits.reverse()
 
  return edits

def main():
    s1 = "algorithm"
    s2 = "alligator"
    print("\n\n")
    print(levenshtein(s1, s2))
    print("\n\n")

main()




This is insertions: 21
This is delete: 21
This is subs: 5
This is insertions: 22
This is delete: 25
This is subs: 7
This is insertions: 23
This is delete: 27
This is subs: 8
This is insertions: 24
This is delete: 28
This is subs: 9
This is insertions: 25
This is delete: 29
This is subs: 10
This is insertions: 26
This is delete: 30
This is subs: 10
This is insertions: 27
This is delete: 30
This is subs: 12
This is insertions: 28
This is delete: 32
This is subs: 13
This is insertions: 29
This is delete: 33
This is subs: 14
This is insertions: 25
This is delete: 22
This is subs: 7
This is insertions: 27
This is delete: 27
This is subs: 10
This is insertions: 28
This is delete: 30
This is subs: 12
This is insertions: 29
This is delete: 32
This is subs: 14
This is insertions: 30
This is delete: 34
This is subs: 15
This is insertions: 30
This is delete: 35
This is subs: 16
This is insertions: 32
This is delete: 36
This is subs: 16
This is insertions: 33
This is delete: 36
This is subs: 18